// SPDX-License-Identifier: GPL-2.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: client_message.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsrCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageTime float32 `protobuf:"fixed32,1,opt,name=message_time,json=messageTime,proto3" json:"message_time,omitempty"`
	Pitch       float32 `protobuf:"fixed32,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Yaw         float32 `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Roll        float32 `protobuf:"fixed32,4,opt,name=roll,proto3" json:"roll,omitempty"`
	Forward     float32 `protobuf:"fixed32,5,opt,name=forward,proto3" json:"forward,omitempty"`
	Side        float32 `protobuf:"fixed32,6,opt,name=side,proto3" json:"side,omitempty"`
	Up          float32 `protobuf:"fixed32,7,opt,name=up,proto3" json:"up,omitempty"`
	Attack      bool    `protobuf:"varint,8,opt,name=attack,proto3" json:"attack,omitempty"`
	Jump        bool    `protobuf:"varint,9,opt,name=jump,proto3" json:"jump,omitempty"`
	Impulse     int32   `protobuf:"varint,10,opt,name=impulse,proto3" json:"impulse,omitempty"`
}

func (x *UsrCmd) Reset() {
	*x = UsrCmd{}
	mi := &file_client_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrCmd) ProtoMessage() {}

func (x *UsrCmd) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrCmd.ProtoReflect.Descriptor instead.
func (*UsrCmd) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{0}
}

func (x *UsrCmd) GetMessageTime() float32 {
	if x != nil {
		return x.MessageTime
	}
	return 0
}

func (x *UsrCmd) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *UsrCmd) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *UsrCmd) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *UsrCmd) GetForward() float32 {
	if x != nil {
		return x.Forward
	}
	return 0
}

func (x *UsrCmd) GetSide() float32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *UsrCmd) GetUp() float32 {
	if x != nil {
		return x.Up
	}
	return 0
}

func (x *UsrCmd) GetAttack() bool {
	if x != nil {
		return x.Attack
	}
	return false
}

func (x *UsrCmd) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *UsrCmd) GetImpulse() int32 {
	if x != nil {
		return x.Impulse
	}
	return 0
}

type Cmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Union:
	//
	//	*Cmd_Disconnect
	//	*Cmd_StringCmd
	//	*Cmd_MoveCmd
	Union isCmd_Union `protobuf_oneof:"union"`
}

func (x *Cmd) Reset() {
	*x = Cmd{}
	mi := &file_client_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd) ProtoMessage() {}

func (x *Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd.ProtoReflect.Descriptor instead.
func (*Cmd) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{1}
}

func (m *Cmd) GetUnion() isCmd_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (x *Cmd) GetDisconnect() bool {
	if x, ok := x.GetUnion().(*Cmd_Disconnect); ok {
		return x.Disconnect
	}
	return false
}

func (x *Cmd) GetStringCmd() string {
	if x, ok := x.GetUnion().(*Cmd_StringCmd); ok {
		return x.StringCmd
	}
	return ""
}

func (x *Cmd) GetMoveCmd() *UsrCmd {
	if x, ok := x.GetUnion().(*Cmd_MoveCmd); ok {
		return x.MoveCmd
	}
	return nil
}

type isCmd_Union interface {
	isCmd_Union()
}

type Cmd_Disconnect struct {
	Disconnect bool `protobuf:"varint,1,opt,name=disconnect,proto3,oneof"`
}

type Cmd_StringCmd struct {
	StringCmd string `protobuf:"bytes,2,opt,name=string_cmd,json=stringCmd,proto3,oneof"`
}

type Cmd_MoveCmd struct {
	MoveCmd *UsrCmd `protobuf:"bytes,3,opt,name=move_cmd,json=moveCmd,proto3,oneof"`
}

func (*Cmd_Disconnect) isCmd_Union() {}

func (*Cmd_StringCmd) isCmd_Union() {}

func (*Cmd_MoveCmd) isCmd_Union() {}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmds []*Cmd `protobuf:"bytes,1,rep,name=cmds,proto3" json:"cmds,omitempty"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_client_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_client_message_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMessage) GetCmds() []*Cmd {
	if x != nil {
		return x.Cmds
	}
	return nil
}

var File_client_message_proto protoreflect.FileDescriptor

var file_client_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0xeb,
	0x01, 0x0a, 0x06, 0x55, 0x73, 0x72, 0x43, 0x6d, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x69, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x69, 0x74,
	0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x79, 0x61, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x75, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x02, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6a, 0x75,
	0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x22, 0x7e, 0x0a, 0x03,
	0x43, 0x6d, 0x64, 0x12, 0x20, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x43, 0x6d, 0x64, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x63,
	0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x55, 0x73, 0x72, 0x43, 0x6d, 0x64, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x65,
	0x43, 0x6d, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x0d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a,
	0x04, 0x63, 0x6d, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x42, 0x23,
	0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65,
	0x72, 0x6a, 0x61, 0x6b, 0x2f, 0x67, 0x6f, 0x71, 0x75, 0x61, 0x6b, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_message_proto_rawDescOnce sync.Once
	file_client_message_proto_rawDescData = file_client_message_proto_rawDesc
)

func file_client_message_proto_rawDescGZIP() []byte {
	file_client_message_proto_rawDescOnce.Do(func() {
		file_client_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_message_proto_rawDescData)
	})
	return file_client_message_proto_rawDescData
}

var file_client_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_client_message_proto_goTypes = []any{
	(*UsrCmd)(nil),        // 0: protos.UsrCmd
	(*Cmd)(nil),           // 1: protos.Cmd
	(*ClientMessage)(nil), // 2: protos.ClientMessage
}
var file_client_message_proto_depIdxs = []int32{
	0, // 0: protos.Cmd.move_cmd:type_name -> protos.UsrCmd
	1, // 1: protos.ClientMessage.cmds:type_name -> protos.Cmd
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_client_message_proto_init() }
func file_client_message_proto_init() {
	if File_client_message_proto != nil {
		return
	}
	file_client_message_proto_msgTypes[1].OneofWrappers = []any{
		(*Cmd_Disconnect)(nil),
		(*Cmd_StringCmd)(nil),
		(*Cmd_MoveCmd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_message_proto_goTypes,
		DependencyIndexes: file_client_message_proto_depIdxs,
		MessageInfos:      file_client_message_proto_msgTypes,
	}.Build()
	File_client_message_proto = out.File
	file_client_message_proto_rawDesc = nil
	file_client_message_proto_goTypes = nil
	file_client_message_proto_depIdxs = nil
}
