// SPDX-License-Identifier: GPL-2.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: savegame.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type StringDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // sname
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringDef) Reset() {
	*x = StringDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDef) ProtoMessage() {}

func (x *StringDef) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDef.ProtoReflect.Descriptor instead.
func (*StringDef) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{1}
}

func (x *StringDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StringDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EntityDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // sname
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EntityDef) Reset() {
	*x = EntityDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDef) ProtoMessage() {}

func (x *EntityDef) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDef.ProtoReflect.Descriptor instead.
func (*EntityDef) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{2}
}

func (x *EntityDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityDef) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FunctionDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // sname
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FunctionDef) Reset() {
	*x = FunctionDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDef) ProtoMessage() {}

func (x *FunctionDef) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDef.ProtoReflect.Descriptor instead.
func (*FunctionDef) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FieldDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // sname
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FieldDef) Reset() {
	*x = FieldDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDef) ProtoMessage() {}

func (x *FieldDef) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDef.ProtoReflect.Descriptor instead.
func (*FieldDef) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{4}
}

func (x *FieldDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FieldDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FloatDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // sname
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FloatDef) Reset() {
	*x = FloatDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatDef) ProtoMessage() {}

func (x *FloatDef) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatDef.ProtoReflect.Descriptor instead.
func (*FloatDef) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{5}
}

func (x *FloatDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FloatDef) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type VectorDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // sname
	Value *Vector `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *VectorDef) Reset() {
	*x = VectorDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDef) ProtoMessage() {}

func (x *VectorDef) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDef.ProtoReflect.Descriptor instead.
func (*VectorDef) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{6}
}

func (x *VectorDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorDef) GetValue() *Vector {
	if x != nil {
		return x.Value
	}
	return nil
}

type Globals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// only globaldefs
	Entities []*EntityDef `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Floats   []*FloatDef  `protobuf:"bytes,2,rep,name=floats,proto3" json:"floats,omitempty"`
	Strings  []*StringDef `protobuf:"bytes,3,rep,name=strings,proto3" json:"strings,omitempty"`
}

func (x *Globals) Reset() {
	*x = Globals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Globals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Globals) ProtoMessage() {}

func (x *Globals) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Globals.ProtoReflect.Descriptor instead.
func (*Globals) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{7}
}

func (x *Globals) GetEntities() []*EntityDef {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Globals) GetFloats() []*FloatDef {
	if x != nil {
		return x.Floats
	}
	return nil
}

func (x *Globals) GetStrings() []*StringDef {
	if x != nil {
		return x.Strings
	}
	return nil
}

type Edict struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// only fielddefs + alpha
	Entities  []*EntityDef   `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Fields    []*FieldDef    `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Floats    []*FloatDef    `protobuf:"bytes,3,rep,name=floats,proto3" json:"floats,omitempty"`
	Functions []*FunctionDef `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
	Strings   []*StringDef   `protobuf:"bytes,5,rep,name=strings,proto3" json:"strings,omitempty"`
	Vectors   []*VectorDef   `protobuf:"bytes,6,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Alpha     float32        `protobuf:"fixed32,8,opt,name=alpha,proto3" json:"alpha,omitempty"`
}

func (x *Edict) Reset() {
	*x = Edict{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edict) ProtoMessage() {}

func (x *Edict) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edict.ProtoReflect.Descriptor instead.
func (*Edict) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{8}
}

func (x *Edict) GetEntities() []*EntityDef {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Edict) GetFields() []*FieldDef {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Edict) GetFloats() []*FloatDef {
	if x != nil {
		return x.Floats
	}
	return nil
}

func (x *Edict) GetFunctions() []*FunctionDef {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Edict) GetStrings() []*StringDef {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Edict) GetVectors() []*VectorDef {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *Edict) GetAlpha() float32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

type SaveGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment      string    `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	SpawnParams  []float32 `protobuf:"fixed32,2,rep,packed,name=spawn_params,json=spawnParams,proto3" json:"spawn_params,omitempty"`
	CurrentSkill int32     `protobuf:"varint,3,opt,name=current_skill,json=currentSkill,proto3" json:"current_skill,omitempty"`
	MapName      string    `protobuf:"bytes,4,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	MapTime      float32   `protobuf:"fixed32,5,opt,name=map_time,json=mapTime,proto3" json:"map_time,omitempty"`
	LightStyles  []string  `protobuf:"bytes,6,rep,name=light_styles,json=lightStyles,proto3" json:"light_styles,omitempty"`
	Globals      *Globals  `protobuf:"bytes,7,opt,name=globals,proto3" json:"globals,omitempty"`
	Edicts       []*Edict  `protobuf:"bytes,8,rep,name=edicts,proto3" json:"edicts,omitempty"`
}

func (x *SaveGame) Reset() {
	*x = SaveGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savegame_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGame) ProtoMessage() {}

func (x *SaveGame) ProtoReflect() protoreflect.Message {
	mi := &file_savegame_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGame.ProtoReflect.Descriptor instead.
func (*SaveGame) Descriptor() ([]byte, []int) {
	return file_savegame_proto_rawDescGZIP(), []int{9}
}

func (x *SaveGame) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SaveGame) GetSpawnParams() []float32 {
	if x != nil {
		return x.SpawnParams
	}
	return nil
}

func (x *SaveGame) GetCurrentSkill() int32 {
	if x != nil {
		return x.CurrentSkill
	}
	return 0
}

func (x *SaveGame) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *SaveGame) GetMapTime() float32 {
	if x != nil {
		return x.MapTime
	}
	return 0
}

func (x *SaveGame) GetLightStyles() []string {
	if x != nil {
		return x.LightStyles
	}
	return nil
}

func (x *SaveGame) GetGlobals() *Globals {
	if x != nil {
		return x.Globals
	}
	return nil
}

func (x *SaveGame) GetEdicts() []*Edict {
	if x != nil {
		return x.Edicts
	}
	return nil
}

var File_savegame_proto protoreflect.FileDescriptor

var file_savegame_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x61, 0x76, 0x65, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x32, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c,
	0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x31, 0x0a, 0x09,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x31, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x33, 0x0a, 0x0b, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a, 0x08, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x44, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a, 0x08, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x44, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x41, 0x0a, 0x09, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8f,
	0x01, 0x0a, 0x07, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x66, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x44, 0x65, 0x66, 0x52, 0x06, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x66, 0x52, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0xad, 0x02, 0x0a, 0x05, 0x45, 0x64, 0x69, 0x63, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x66, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x66, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x44, 0x65, 0x66, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x73, 0x12, 0x31, 0x0a,
	0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x66, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x2b, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x44, 0x65, 0x66, 0x52, 0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x2b, 0x0a,
	0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65,
	0x66, 0x52, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x22, 0x97, 0x02, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x70, 0x61, 0x77, 0x6e,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0b, 0x73,
	0x70, 0x61, 0x77, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61,
	0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6d, 0x61,
	0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73,
	0x74, 0x79, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x67, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x52, 0x07, 0x67, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x65, 0x64, 0x69, 0x63, 0x74, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x64, 0x69,
	0x63, 0x74, 0x52, 0x06, 0x65, 0x64, 0x69, 0x63, 0x74, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x72, 0x6a, 0x61, 0x6b,
	0x2f, 0x67, 0x6f, 0x71, 0x75, 0x61, 0x6b, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_savegame_proto_rawDescOnce sync.Once
	file_savegame_proto_rawDescData = file_savegame_proto_rawDesc
)

func file_savegame_proto_rawDescGZIP() []byte {
	file_savegame_proto_rawDescOnce.Do(func() {
		file_savegame_proto_rawDescData = protoimpl.X.CompressGZIP(file_savegame_proto_rawDescData)
	})
	return file_savegame_proto_rawDescData
}

var file_savegame_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_savegame_proto_goTypes = []interface{}{
	(*Vector)(nil),      // 0: protos.Vector
	(*StringDef)(nil),   // 1: protos.StringDef
	(*EntityDef)(nil),   // 2: protos.EntityDef
	(*FunctionDef)(nil), // 3: protos.FunctionDef
	(*FieldDef)(nil),    // 4: protos.FieldDef
	(*FloatDef)(nil),    // 5: protos.FloatDef
	(*VectorDef)(nil),   // 6: protos.VectorDef
	(*Globals)(nil),     // 7: protos.Globals
	(*Edict)(nil),       // 8: protos.Edict
	(*SaveGame)(nil),    // 9: protos.SaveGame
}
var file_savegame_proto_depIdxs = []int32{
	0,  // 0: protos.VectorDef.value:type_name -> protos.Vector
	2,  // 1: protos.Globals.entities:type_name -> protos.EntityDef
	5,  // 2: protos.Globals.floats:type_name -> protos.FloatDef
	1,  // 3: protos.Globals.strings:type_name -> protos.StringDef
	2,  // 4: protos.Edict.entities:type_name -> protos.EntityDef
	4,  // 5: protos.Edict.fields:type_name -> protos.FieldDef
	5,  // 6: protos.Edict.floats:type_name -> protos.FloatDef
	3,  // 7: protos.Edict.functions:type_name -> protos.FunctionDef
	1,  // 8: protos.Edict.strings:type_name -> protos.StringDef
	6,  // 9: protos.Edict.vectors:type_name -> protos.VectorDef
	7,  // 10: protos.SaveGame.globals:type_name -> protos.Globals
	8,  // 11: protos.SaveGame.edicts:type_name -> protos.Edict
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_savegame_proto_init() }
func file_savegame_proto_init() {
	if File_savegame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_savegame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Globals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edict); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savegame_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_savegame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_savegame_proto_goTypes,
		DependencyIndexes: file_savegame_proto_depIdxs,
		MessageInfos:      file_savegame_proto_msgTypes,
	}.Build()
	File_savegame_proto = out.File
	file_savegame_proto_rawDesc = nil
	file_savegame_proto_goTypes = nil
	file_savegame_proto_depIdxs = nil
}
