#ifndef HASCANVAS
#define HASCANVAS
typedef enum {
  CANVAS_NONE,
  CANVAS_DEFAULT,
  CANVAS_CONSOLE,
  CANVAS_MENU,
  CANVAS_SBAR,
  CANVAS_WARPIMAGE,
  CANVAS_CROSSHAIR,
  CANVAS_BOTTOMLEFT,
  CANVAS_BOTTOMRIGHT,
  CANVAS_TOPRIGHT,
  CANVAS_INVALID = -1
} canvastype;
#endif
